[package]
name = "bifrost"
version = "0.1.0"
authors = ["Martin Algesten <martin@algesten.se>"]
edition = "2018"

[dependencies]
clap = "2"
ureq = "*"

[dev-dependencies]
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
